# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
    CODE_DIR:     'jlox/com/craftinginterpreters/lox'
    CODE_PATH:    '{{.CODE_DIR}}/*.java'
    CODE_PACKAGE: 'com.craftinginterpreters.lox.Lox'

    TOOL_DIR:     'jlox/com/craftinginterpreters/tool'
    TOOL_PATH:    '{{.TOOL_DIR}}/*.java'
    TOOL_PACKAGE: 'com.craftinginterpreters.tool.GenerateAst'

    OUT_DIR:  'jlox/out'
    TEST_DIR: 'tests'
    TEST:     '{{.TEST_DIR}}/test.lox'

tasks:
    build:
        sources:
            - '{{.CODE_PATH}}'
        generates:
            - '{{.OUT_DIR}}/**/*.class'
        cmds:
            - javac -d {{.OUT_DIR}} {{.CODE_PATH}}
        silent: true
    
    run:
        cmds:
            - java -cp {{.OUT_DIR}} {{.CODE_PACKAGE}}
        silent: true
    
    tool:
        sources:
            - '{{.TOOL_PATH}}'
        generates:
            - '{{.CODE_DIR}}/Expr.java'
        cmds:
            - javac -d {{.OUT_DIR}} {{.TOOL_PATH}}
            - java -cp {{.OUT_DIR}} {{.TOOL_PACKAGE}} {{.CODE_DIR}}
        silent: true
    
    clean:
        cmds:
            - rm -rf {{.OUT_DIR}}
        silent: true
    
    test:
        deps: [build]
        cmds:
            - java -cp {{.OUT_DIR}} {{.CODE_PACKAGE}} {{.TEST}}
        silent: true
    
    default:
        cmds:
            - task: build
            - task: run